src/app/services/eventdisplay.service.ts
src/app/services/loaders/event-data-loader.ts
src/app/services/loaders/phoenix-loader.ts
src/app/services/three.service.ts
src/app/services/ui.service.ts

- Improved export and import 
Here I tackle odd behavior while exporting and importing a scene. I introduce list of object to not export, since they are not well supported in current GLTF versions. The objects that are excluded are considered a defaults and are loaded at scene initialization.
- Fixed views animation to work on arbitrary transform 
Views animation did not seem to work in arbitrary position and rotation. Adding both animations fixed the problem. I also added animation to other align view options.
- Fixed muons color property
There was an error while tiring to change a muon color. Since muons are compound objects, changing the depth of material color assignment solved this issue. 
-  Formatting and fixing event data loading
Changed event data loading to a more consistent …

General improvements and fixes

---

src/app/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
src/app/components/ui-menu/object-selection/object-selection-overlay/object-selection-overlay.component.html
src/app/services/three.service.ts

Hi,
Some draggable components can be dragged outside the browser window view and can become impossible to fetch again.
This fix limits their movement so they can't go out of the browser window.
The changes effect and limit drag movements of **Overlay view**, **Object selection**, and **Event data collections info**.

Restrict movement of draggable components

---

src/app/services/loaders/phoenix-loader.ts

Fixes #56
The code uses Object keys to get the cuts. Since the key for momentum being used in the code was `momentum`, the code wasn't picking `mom` which is the actual momentum property of tracks in events.

Fix momentum cuts not working

---

src/app/services/three.service.ts
src/app/services/ui.service.ts

Hi,
Added a toggle to change the depthTest of event data. This helps in toggling to show event data on top of detector geometry. It actually works equally well for all experiments. We can see both the geometry and the complete event at the same time. :)
Here is how it looks:

Toggle for changing event data depthTest

---

src/app/services/three.service.ts
src/app/services/ui.service.ts

Hi,
Since a group with identifier `SceneManager.GEOMETRIES_ID` is being used to group all detector geometries, geometries loaded from gltf should also be a part of this group.
The `Geometries` folder `Show` checkbox wasn't working because of this.
Thanks. :)

Show/hide all geometries not working for geometries loaded from GLTF

---

src/app/services/three/scene-manager.ts
src/app/services/ui.service.ts

Hi,
Added a toggle for wireframing detector geometry and decreasing it's opacity for a better event view. Here's how it looks:

Add toggle for wireframing geometries

---

src/app/services/loaders/lhcb-loader.ts
src/app/services/loaders/phoenix-loader.ts

Hi,
The `getCollection` and `getCollections` functions were not checking for possible undefined values in event data collections. This could have been fixed by just changing the `lhcb-loader.ts` `Hits` to an empty object but since users can also put values like this, it's better to check if there is a value before iterating.
**Before:**
**After:**
Thanks. :)

Fix LHCb loader bug of loading collections

---

src/app/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
src/app/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.scss
src/app/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts
src/app/components/ui-menu/event-selector/event-selector.component.scss
src/app/components/ui-menu/overlay/overlay.component.scss
src/app/services/eventdisplay.service.ts
src/app/services/loaders/objects/phoenix-objects.ts
src/app/services/loaders/phoenix-loader.ts
src/app/services/three.service.ts
src/app/services/three/controls-manager.ts
src/app/services/three/scene-manager.ts
src/app/services/three/selection-manager.ts
src/styles.scss

Fixes #93 
Hi,
Updated the collections info panel so that selection in the scene will highlight the event data items in the collections info panel and users can also highlight or move to objects in the scene from the collections info panel.
* Highlight event data in collections info panel on selection of event object from the scene
* Highlight event data in the scene on selection of event data from the collections info panel
* Ability to highlight and move camera to object from the collections info panel
* Works for all event data including Tracks, Muons, Hits and Clusters
* Two different options "Move camera to object" and "Highlight object" for highlighting event data from collections info panel
* Some fixes to the collections info panel
* A combination of `Tube` and `Line` for better …

Selection of 3D object from collections info panel

---

src/app/services/loaders/objects/phoenix-objects.ts
src/app/services/loaders/phoenix-loader.ts
src/app/services/three/scene-manager.ts
src/app/services/ui.service.ts

Closes #103 
Hi,
This makes the Jets scalable and also allows to extend UI menu options for each object type which can be used with any loader (by using the `PhoenixLoader.addObjectType` method from a child class).
I have been trying out options to scale Jets since yesterday but removing and recreating the Jets with increased energy wasn't working for large number of Jets. So after a lot of tries I came up with a minimal method which I think is the best.
* Fixed depthTest not working correctly
* Removed custom synchronous function to loop through children for changing depthTest (I am not sure why but `Object3D.traverse` seems to work now - while depthTest only worked with `updateChildrenDepthTest` function earlier)
* Made Jets scalable by increasing their scale and changing their position …

Scalable Jets and fix depthTest

---

src/app/sections/cms/cms.component.ts
src/app/services/loaders/cms-loader.ts

Hi,
This enables loading data of all events from an ".ig" file in the CMS section of Phoenix.
* A function to get data of all events from ".ig" file in a format suitable for Phoenix
* Loading all events from ".ig" file using `EventDisplay.parsePhoenixEvents` which adds the option to select any event from the UI menu

Loading data of all events in CMS

---

src/app/sections/atlas/atlas.component.ts
src/app/services/eventdisplay.service.ts
src/app/services/three.service.ts
src/app/services/ui.service.ts

Closes #106 
Hi,
This adds option for making the geometry initially invisible through the geometry loading functions.
**NOTE:** @EdwardMoyse let me know which geometries from ATLAS are to be made initially invisible. I will push to this PR once I know.
* Added param `initiallyVisible: boolean = true` to `loadOBJGeometry`, `parseOBJGeometry`,  `loadGLTFGeometry` and `loadJSONGeometry` functions of `EventdisplayService` for making geometry invisible (initiallyVisible = false) by default
* Fix preset views not loading (set the configuration property of `UIService` through `showUI` instead of `showDatGUIMenu` since dat.GUI menu is optional now)
(With "Toroids" and "Tile Cal" initially invisible)

Option to load geometry on demand

---

src/app/components/phoenix-menu/phoenix-menu-node/phoenix-menu-node.ts
src/app/sections/cms/cms.component.ts
src/app/services/ui.service.ts

Hi,
This fixes a bug in which the phoenix menu geometries (Detector folder/node) were not repopulating when navigating from one experiment to another and back. The reason was that the phoenix menu was not properly re instantiated in the UI service.
* Proper clear operations for phoenix menu in UI service
* Redefining the phoenix menu root node for UI service
* Nullifying of phoenix menu nodes/folders for recreating them

Fix geometries not repopulating in phoenix menu

---

src/app/components/ui-menu/overlay-view/overlay-view.component.ts
src/app/services/eventdisplay.service.ts
src/app/services/three.service.ts
src/app/services/three/renderer-manager.ts
src/app/services/ui.service.ts

**Note:** To be merged after PR 118 
Hi,
This adds keyboard controls for common event display and three service functions.
* Keyboard controls for
* Toggling theme (`shift + t`)
* Going to preset view (`shift + 1..9` - 1 to 9 is the index of preset view with 1 being the first preset view)
* Autorotate (`shift + r`)
* Zoom in (`shift + "+"`)
* Zoom out (`shift + "-"`)
* 180° Clipping (`shift + c`)
* Toggling view (`shift + v`)

Keyboard controls

---

src/app/services/extras/runge-kutta.ts
src/app/services/helpers/rk-helper.ts
src/app/services/loaders/jivexml-loader.ts
src/app/services/loaders/objects/phoenix-objects.ts
src/app/services/loaders/phoenix-loader.ts

This adds some new types of objects to Phoenix (not all can be displayed yet) and also adds the ability to truncate the Track extrapolation at a Volume. For example, for ATLAS it doesn't really make sense to extrapolate tracks past the entrance to the calorimeter.
This is not very elegant TypeScript - @9inpachi I'd appreciate a code review! I bet there are better ways to do a lot of this, especially the changes to the RK, and the conditional checks on the JiveXML contents (some tracks have some variables, which are missing on others).
There is one *big* problem at the moment - opening some jiveXML is very very slow (it does eventually complete) because the tracks are very low transverse momenta and so get extrapolated a long way. I think the path length and step size could help, but also …

[WIP] Jive xml improvements

---

.travis.yml
packages/phoenix-app/package-lock.json
packages/phoenix-app/src/app/components/phoenix-menu/pheonix-menu-item/phoenix-menu-item.component.html
packages/phoenix-event-display/src/event-display.ts
packages/phoenix-event-display/src/extras/configuration.model.ts
packages/phoenix-event-display/src/helpers/constants.ts
packages/phoenix-event-display/src/loaders/objects/cms-objects.ts
packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
packages/phoenix-event-display/src/loaders/phoenix-loader.ts
packages/phoenix-event-display/src/three/index.ts
packages/phoenix-event-display/src/ui/index.ts
packages/phoenix-event-display/src/ui/phoenix-menu/phoenix-menu-node.ts

Hi,
This adds feature to save and load configuration aka state of the Phoenix menu with effects to the scene (like event data color, geometry opacity etc.). This works well for all configurations in the Phoenix menu. It saves the Phoenix menu state as a `json` file which can later be loaded. The state can also be loaded directly from code (using `PhoenixMenuNode.loadStateFromJSON(json: object } string)`.
It works REALLY WELL and will be very useful. I didn't think it would turn out this good.
The PR includes some other fixes and improvements as well.
* Save state of the Phoenix menu as JSON  
* Save state of the node like the toggle state, all configuration options (like color and slider values) of the node and the state of all its children
* Process and load the state of the Phoenix menu …

Save and load Phoenix menu state

---

packages/phoenix-event-display/src/loaders/jivexml-loader.ts
packages/phoenix-event-display/src/loaders/phoenix-loader.ts

I noticed that the pT cuts weren't appearing for Tracks and decided to investigate
I also decided to add a few missing cuts
There are a few issues here. One, is that the cuts are very atlas-specific, so they should really be added by the JiveXML loader.
Another is that I don't think there is a way at the moment to add e.g. x,y,z cuts when the property is just a 3 dim array.

Add more cuts

---

packages/phoenix-event-display/src/three/index.ts
packages/phoenix-event-display/src/three/renderer-manager.ts
packages/phoenix-ng/angular.json
packages/phoenix-ng/projects/phoenix-app/src/assets/icons/ss-mode.svg
packages/phoenix-ng/projects/phoenix-ui-components/src/assets/icons/ss-mode.svg
packages/phoenix-ng/projects/phoenix-ui-components/src/components/phoenix-ui.module.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/index.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ss-mode/ss-mode.component.html
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ss-mode/ss-mode.component.scss
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ss-mode/ss-mode.component.spec.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ss-mode/ss-mode.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ui-menu.component.html

Hi,
This adds a toggle to enable screenshot mode in which all overlay elements (UI menu, Phoenix menu etc.) are hidden except the experiment info overlay.
* Toggle in UI menu for screenshot mode
* Ability to close screenshot mode on click or on escape key press
* Tests for the screenshot mode component

Support for screenshot mode

---

packages/phoenix-ng/README.md
packages/phoenix-ng/angular.json
packages/phoenix-ng/package.json
packages/phoenix-ng/projects/phoenix-app/event-config.json
packages/phoenix-ng/projects/phoenix-app/src/app/app.module.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts
packages/phoenix-ng/projects/phoenix-app/src/environments/environment.single.ts
packages/phoenix-ng/projects/phoenix-app/src/environments/environment.ts
packages/phoenix-ng/projects/phoenix-app/tsconfig.app.json
packages/phoenix-ng/tsconfig.json

Closes #149 
Closes #163
Hi,
This adds support for starting or deploying Phoenix with a specific event that a user can specify in a configuration file.
* A new `environment.single.ts` file for specifying configuration to deploy Phoenix with a specific event
* A configuration file `event-config.json` (`phoenix-app/event-config.json`) which specifies the event file and type to be used for Phoenix with a single event
* Scripts for starting and deploying Phoenix with a specific event
* Code for different behavior when Phoenix with a specific event is to run or deploy
Instructions specified in [phoenix-ng README](https://github.com/9inpachi/phoenix/tree/feat-deploy-with-event/packages/phoenix-ng#readme).
For only running the app with a specific event, use `npm run start:single` from the …

Support to start or deploy Phoenix with a specific event

---

packages/phoenix-event-display/src/event-display.ts
packages/phoenix-event-display/src/ui/index.ts
packages/phoenix-event-display/src/ui/phoenix-menu/phoenix-menu-node.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/cms/cms.component.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/trackml/trackml.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ss-mode/ss-mode.component.ts

Closes #171 
Hi,
This adds support to add geometries to a folder / node in Phoenix menu. The geometries can also be added in multi level node hierarchies.
* Ability to add geometry to a menu folder
* Ability to specify the folder hierarchy to add the geometry to multilevel Phoenix menu folder.
Misc
* Full screen in screenshot mode
For example, if we want to add an `OBJ` geometry to  the "Inner Detector" folder inside the "Detector" folder of Phoenix menu.
```js
EventDisplay.loadOBJGeometry('path/to/object.obj', 'Geometry', 0xffffff, 'Inner Detector');
```
And if we want to add an `OBJ` geometry to  the "Pixel" folder inside the "Inner Detector" folder which will be inside the "Detector" folder of Phoenix menu. The `>` works as a separator for specifying the hierarchy.
```js …
```

Ability to add geometry to a folder

---

packages/phoenix-event-display/src/event-display.ts
packages/phoenix-event-display/src/three/index.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/geometry/geometry.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/geometry/geometry.component.scss
packages/phoenix-ng/projects/phoenix-app/src/app/sections/geometry/geometry.component.ts

Get the geometry demo working properly again.
The problem was the code to draw parametrised geometry was lost in the move to angular. So I re-implemented this, and added two new functions:
- buildGeometryFromParameters to EventDisplay
- addGeometryFromParameters to ThreeManager
Thanks to @9inpachi for the help!

Fix geometry demo

---

packages/phoenix-event-display/src/three/controls-manager.ts
packages/phoenix-event-display/src/three/index.ts

Closes #178
Hi,
This hides the tube tracks when the camera gets closer to the origin within 200 radius.
**NOTE:** THIS IS FOR ALL EXPERIMENTS
* Function to enable the behavior of hiding tube tracks on zoom

Hide tube tracks on zoom

---

packages/phoenix-event-display/src/event-display.ts
packages/phoenix-event-display/src/extras/configuration.ts
packages/phoenix-event-display/src/loaders/phoenix-loader.ts
packages/phoenix-event-display/src/managers/url-options-manager.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/cms/cms.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/trackml/trackml.component.html

This adds an option to hide all overlay widgets through a URL parameter.
Set the `hideWidgets` parameter in the URL.
Examples:
http://localhost:4200/#/cms?hideWidgets=true
http://phoenix-pr-214.surge.sh/#/atlas?hideWidgets=true
* Create a `URLOptionsManager` for easily extending URL options
* Ability to hide all overlay widgets with a URL parameter
* Other code optimizations

URL options manager with option to hide all overlay widgets

---

packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.html
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.spec.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts

Closes #232 
This adds support for importing zip files with event data in either JiveXML or JSON format.
* Ability to import event data from zip file with both JiveXML or JSON inside the zip  
* All are loaded and available through the event selection list in UI menu
* Add and update tests for `IOOptionsDialog`
* Fix error caused when there are no track positions in JSON event data

Open compressed event data

---

packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
packages/phoenix-event-display/src/loaders/phoenix-loader.ts
packages/phoenix-event-display/src/three/scene-manager.ts

Follow up to discussion on PR #257
Allows to scale clusters just in z direction (but made this a general feature of `scaleChildObjects`)

feat(event-display): add ability to scale clusters in just one direction

---

packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
packages/phoenix-ng/projects/phoenix-app/src/assets/files/event_data/atlaseventdump2.json

I accidentally broke reading older Events with a (IMO) bad design for hits. Now tries to handle simple arrays again.
Fixed the example JSON files.

fix(event-display): handle older json hit format again

---

packages/phoenix-event-display/src/managers/loading-manager.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/cms/cms.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/cms/cms.component.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/geometry/geometry.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/geometry/geometry.component.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/playground/playground.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/playground/playground.component.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/trackml/trackml.component.html
packages/phoenix-ng/projects/phoenix-app/src/app/sections/trackml/trackml.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/_theming.scss
packages/phoenix-ng/projects/phoenix-ui-components/src/components/loader/loader.component.html
packages/phoenix-ng/projects/phoenix-ui-components/src/components/loader/loader.component.scss
packages/phoenix-ng/projects/phoenix-ui-components/src/components/loader/loader.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ui-menu.component.html
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ui-menu.component.scss

This adds a loading progress bar based on the number of items loaded. A next step would be to use `LoadingManager.onProgress(id: string, progress: number)` to supply progress of each geometry loaded if the geometry loader supports it.
* Allow content in UI menu for displaying custom menu items
* Use linear row for UI menu items
* Add loading progress in `LoadingManager` based on number of items loaded
* Add loading progress to all experiments.

Support for loading progress

---

packages/phoenix-event-display/src/loaders/phoenix-loader.ts
packages/phoenix-event-display/src/managers/state-manager.ts
packages/phoenix-event-display/src/managers/three-manager/color-manager.ts
packages/phoenix-event-display/src/managers/ui-manager/color-options.ts
packages/phoenix-event-display/src/managers/ui-manager/dat-gui-ui.ts
packages/phoenix-event-display/src/tests/managers/three-manager/index.spec.ts
packages/phoenix-ng/projects/phoenix-ui-components/_theming.scss
packages/phoenix-ng/projects/phoenix-ui-components/src/components/phoenix-menu/pheonix-menu-item/phoenix-menu-item.component.html
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/share-link/share-link-dialog/share-link-dialog.component.scss

Closes #311 
Hi,
This fixes the the color by vertex option and colors tracks associated with vertices based on the vertex color instead of a random color.
* Added button in color options to randomly color collections
* Tracks associated with vertices are now colored the same as the vertices
* Fix bug in scaling of Jets in dat.GUI menu
* Fix bug in trying to load configuration without Phoenix menu
* Improve styling and colors for dialogs

Fix color by vertex and add option to randomly color collections

---

packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts

Greetings, 
So in these 2 commits I fix a bit the performance of the geometry caused by the VP subdetector because of it's many many layers of complexity from the .root level. I tried to remove all the volumes from the root file that would not harm the 3D modeling of the particular subdetector and right now as it is anything else can't be removed without having a visual impact on the actual geometry model. The minor fps boost is right now on my machine at around 14 fps on a laptop without a GPU. Disabling the VP geometry from the menu makes it 40 fps. But even on 14 fps it is pretty usable and fast, significantly faster than the previous 3-5 fps 😝 . 
I also fixed a bug in the Rich geometry, in particular there are 2 Rich subdetectors in LHCb and when disabling them in the menu on the …

Fix a bit the performance of the LHCb geometry, some small bugs

---

packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
packages/phoenix-event-display/src/managers/three-manager/ar-manager.ts
packages/phoenix-event-display/src/managers/three-manager/xr-manager.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.scss
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.spec.ts
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts

Closes #347
Closes #272
This shows objects that are cut in the collections info panel by decreasing opacity of the rows. @EdwardMoyse, let me know if this is fine by you.
* Optimize handling of pretty symbols in collections info panel
* Add functionality to check if the object is hidden in the scene
* Fix and update tests for collections info panel

Show cuts in collections info panel

---

CONTRIBUTING.md
packages/phoenix-event-display/src/event-display.ts
packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-node.ts

With this we can manually remove parts of the Phoenix menu configuration and then the value from code will be used.
@EdwardMoyse This will be useful for managing geometries through URL options.

Do not apply Phoenix menu node toggle if undefined

---

packages/phoenix-event-display/README.md
packages/phoenix-event-display/configs/webpack.conf.js

This configures the webpack bundle to not include three.js, instead it's treated as an external dependency. The size of the Phoenix bundle is then reduced to about half (from ~1 MB to 441 KB).

Make three.js an external dependency for the webpack bundle

---

packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.scss
packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts

Added sorting in both ascending & descending order with respect to a particular column in collections table, but for columns with numerical input only.

Sort column feature on collections table

---

packages/phoenix-event-display/src/tests/managers/three-manager/index.spec.ts
packages/phoenix-event-display/src/tests/managers/ui-manager/index.spec.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/object-clipping/object-clipping.component.spec.ts

This PR addresses: https://github.com/HSF/phoenix/runs/5775474777?check_suite_focus=true
Ran checks locally after doing the changes -
Please let me know if something needs to change. 🙂

Fix failing tests for ThreeManager and UIManager for stable CI job

---

packages/phoenix-event-display/src/extras/configuration.ts
packages/phoenix-event-display/src/managers/three-manager/import-manager.ts
packages/phoenix-event-display/src/managers/three-manager/index.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/object-clipping/object-clipping.component.html

A few improvements have been made to clipping : 
- the user visible clipping planes are no more polluted by the internal clipping implementation
- the internal clipping implementation supports clipping up to 360 degrees
- and the gui has been adapted to be able to use it
There is however still a problem in case of user defined clipping when the clipping angle of the internal clipping in > 180 degrees. In such a case, the internal clipping needs to switch to union mode, which will apply to the user clipping and may result in weird behavior. Now it seems that user clipping was only used by LHCb for unknown reasons and I will soon drop it. So maybe we should rather drop that (just introduced) feature for now.

Improvements in clipping

---

packages/phoenix-event-display/src/tests/managers/three-manager/index.spec.ts

Context: https://github.com/HSF/phoenix/pull/435#issuecomment-1122124434
Although, that one got fixed. I'm still seeing one more error here in the `phoenix-ng` package:   
`Chrome Headless 101.0.4951.54 (Windows 10) IoOptionsDialogComponent should handle zipped event data FAILED`.  
After this change, full stack trace 👇  
```  
$ lerna run test:coverage
lerna notice cli v4.0.0
lerna info Executing command in 2 packages: "yarn run test:coverage"
phoenix-ng: $ rimraf ./coverage && ng test phoenix-ui-components --no-watch --code-coverage --no-progress --browsers=ChromeHeadlessCI --source-map=false
phoenix-event-display: $ yarn test
phoenix-event-display: $ karma start configs/karma.conf.js --browsers=ChromeHeadlessCI
phoenix-event-display: DATETIME:INFO [compiler.karma-typescript]: Compiling …
```

Fix failing tests for ThreeManager

---

packages/phoenix-event-display/src/managers/three-manager/import-manager.ts

This is done via an "opacity" entry in the userData fields of a geometry

Allow to specify default opacity in GLTF files

---

packages/phoenix-ng/projects/phoenix-app/src/polyfills.ts
packages/phoenix-ng/projects/phoenix-app/src/zone-flags.ts
packages/phoenix-ng/projects/phoenix-app/tsconfig.app.json

This is a first attempt to optimize the rendering speed of phoneix.
Due to other issues, it's not really making an immediate difference, but it removes a first show stopper
All credits go to Arthur Hennequin of the LHCb experiment

Disable angular change check at every frame

---

guides/developers/README.md
guides/developers/convert-gdml-to-gltf.md
guides/developers/set-up-phoenix.md
guides/users.md
packages/phoenix-event-display/src/lib/models/preset-view.model.ts

Still work in progress. To be done :

Adding documentation on latest improvements + missing parts

---

packages/phoenix-event-display/src/loaders/phoenix-loader.ts

In particular an event with event number 0 had no event number displayed.
Was just a stupid mistake due to javascript lack of type safety
@kjvbrt for info

Fixed handling of event properties

---

packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts

This actually fixes most of the problems of objects not shown inside a transparent volume.
@9inpachi @EdwardMoyse  Out of curiosity : is there really a reason to have this default transparency explicit, and be able to set it to true ? It kind of breaks the attempts of three.js of rendering things properly by rendering non transparent objects first and transparent ones only after.

Set transparency to false by default for LHCb

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/phoenix-menu/phoenix-menu-item/phoenix-menu-item.component.html
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/phoenix-menu/phoenix-menu-item/phoenix-menu-item.component.scss

Within ATLAS we have had issues where the jets or cells aren't visible because the upper bound range is too low. We can change this in the code, but that's not very helpful if we have a special event. Also, it's quite fiddly to do cuts with the slider sometimes.
So this is a WIP to add manual entries. Currently it looks like (you can see I haven't worried about styling yet).
Currently, this isn't really working anyway - entered values don't move the slider or update the display, so the link isn't working.
I tried moving to use ` <input type="number" [(ngModel)]="value">` in `phoenix-menu-item.component.html, but then I get:
```
Error: projects/phoenix-ui-components/lib/components/phoenix-menu/phoenix-menu-item/phoenix-menu-item.component.html:126:32 - error TS2339: Property 'value' does …
```

Add manual inputs for range cuts

---

packages/phoenix-event-display/src/managers/three-manager/import-manager.ts
packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-ui.ts

In case of 2 objects with identical name "Mirror" living in 2 different menus "Rich1" and "Rich2", it was so far impossible to identify them uniquely, as both names were just "Mirror".
With this change, the names are "Rich1 > Mirror" and "Rich2 > Mirror". Menu display has been adapted so that it stays the same

Use full path for object names

---

Dockerfile

After updating JSROOT to v7, the docker image failed to build because of transitive dependency on node's `canvas` and `gl` packages which need special packages for compilation. This PR makes the necessary changes so the docker image can be built again.

Fix Dockerfile for release to docker hub

---

packages/phoenix-event-display/src/event-display.ts

When loading event data from JSON file in the playground, eventDataLoader is missing.

Checking if eventDataLoader exists

---

guides/developers/event_data_format.md
packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts

It seems different experiments started with different conventions here. It was simple enough to support both, so I implemented it

Make Vertices support both pos and x/y/z definitions + updated doc

---

guides/developers/README.md
guides/developers/geometry-tips.md
packages/phoenix-event-display/src/managers/three-manager/import-manager.ts
packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts

This migrates LHCb to compressed glb (generated with: `gltf-pipeline -i LHCb.gltf -o LHCb.glb -d`)
This reduces the size of the geometry from 19Mb to 7.2Mb
To uncompress the geometry, we need to add the `DRACOLoader` (see the discussion in #529)
In my local tests this doesn't really improve anything. However I would expect it might running remotely... however I need to test this (hopefully I can use the deployment here to do so).
cc @sponce

Move LHCb to use Draco and LHCb.glb

---

guides/users.md
packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
packages/phoenix-event-display/src/loaders/phoenix-loader.ts

Calorimeter cells with arbitrary polyhedron-type geometry. 
Each cell is represented by 8 (x,y,z) vertices connected using a convex hull from the [ConvexGeometry](https://threejs.org/docs/#examples/en/geometries/ConvexGeometry) class.
IrregularCaloCells is a list of objects with the following attributes :
* `layer` - the Calorimeter layer
* `vtx` - a flattened list of 8 vertex coordinates (24 floats)
* `color` - an integer list of [R,G,B] values
* `opacity` - value from 0 to 1

Adding support for IrregularCaloCells physics objects

---

packages/phoenix-event-display/src/loaders/edm4hep-json-loader.ts
packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts

Adding support for the edm4hep (sim)trackerhits to be visualized as circular points.
Also: adds `uuid` to the irregular calo cells object

Adding support for edm4hep tracker hits

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/overlay-view/overlay-view-window/overlay-view-window.component.html
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/overlay/overlay.component.ts

Fixed issue [Overlay resize not fully working #467](https://github.com/HSF/phoenix/issues/467). When switching to overlay view, resizing the overlay view window poses an issue by keeping some blank space in the vertical direction. It has been fixed by locking the aspect ratio of the overlay window as shown below.
https://user-images.githubusercontent.com/77807055/222975101-e13b09af-1378-44de-b950-2cc205ff16d2.mp4

Fix overlay view resizing issue

---

packages/phoenix-event-display/src/lib/types/configuration.ts
packages/phoenix-event-display/src/managers/ui-manager/index.ts

One request we had from ATLAS was to be able to force the colour scheme. Since (I think) we don't save the status of the configuration bar in the 'save state' json, I figured this was the only other work around.

Add forceColourTheme configuration option

---

packages/phoenix-event-display/src/managers/ui-manager/color-options.ts
packages/phoenix-ng/jest.config.js
packages/phoenix-ng/package.json
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/phoenix-menu/phoenix-menu-item/phoenix-menu-item.component.html
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/phoenix-menu/phoenix-menu-item/phoenix-menu-item.component.scss
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/phoenix-ui.module.ts
packages/phoenix-ng/projects/phoenix-ui-components/package.json
yarn.lock

Closes #566
Since ngx-slider consumes a lot of memory when building/opening Phoenix menu items, it is removed to fix the problem of Phoenix menu items taking too long to open.

Fix phoenix menu performance by removing ngx-slider

---

.github/workflows/main.yml
.github/workflows/release.yml
guides/release.md
package.json

Closes #574 
Currently, we do the release by following the [release guide](https://github.com/HSF/phoenix/blob/26c507202114625c70f483c5f317fb0f8a089f9b/guides/release.md). With this update, we will be able to automate the release by just having the ability to trigger it as a GitHub action and specifying the type of the next version update.
- Some improvements to the main build and test action.
- Add a new job to the release workflow  whcih runs on manual dispatch, publishes the packages to npm and goes through the release process.
- Update the documentation of release process.

Automate the release process

---

.github/workflows/main.yml

Since we switched the default branch to `main`, the automated deployment to dev is not working. This fixes the issue by renaming master to main in the GitHub Actions workflow.

Fix dev deployment

---

README.md

This pull request addresses a minor issue in the README.md file where the word "yarn" was not capitalized.

Fix: capitalization of "yarn" in README.md

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/cycle-events/cycle-events.component.html
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/cycle-events/cycle-events.component.scss
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/cycle-events/cycle-events.component.test.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/cycle-events/cycle-events.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/event-data-explorer/event-data-explorer-dialog/event-data-explorer-dialog.component.test.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/event-data-explorer/event-data-explorer-dialog/event-data-explorer-dialog.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/services/file-loader.service.component.test.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/services/file-loader.service.ts

First moved file loading code from the ui component event-data-explorer-dialog to the dedicated service file-loader, for easier reuse
Then added auto reload event features to the cycle-event component
The component now toggles between 3 modes :
- no cycle
- cycle as before over existing events
- cycle and reload events when reaching the end
Last mode allows for easy live feed providing the source is a URL
On the way, 2 little bugs have been fixed :
- start the cycle on first event and not a random number that may be past the last event and fail
- not mess up with event numbers when changing the set of events, again could lead to be past last event and fail
- immediately start the cycle when clicking, not waiting for a first interval

Auto reload feature for cycle-event component

---

packages/phoenix-event-display/src/loaders/edm4hep-json-loader.ts
packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts

Adding possibility to specify opacity for a calorimeter cell.

feat(event-display): calo cell opacity

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/make-picture/make-picture.component.test.ts

Basically reverting commit bb81ea87374806f615ac7624604098b07f992a6d which dropped it, but also fixing the test
Fixes #544

Reintroduced make-picture-component.test

---

packages/phoenix-event-display/src/event-display.ts
packages/phoenix-event-display/src/managers/three-manager/index.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/make-picture/make-picture.component.html
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/make-picture/make-picture.component.scss
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/make-picture/make-picture.component.test.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/make-picture/make-picture.component.ts

If the size requested is too high, one can no more create the picture. This avoids distorded picture, waiting for a proper implementation for huge pictures.
This implements the first point of #581

Implemented size checking in make-picture

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/cycle-events/cycle-events.component.html

This has been broken when the cycle+reload state was added

Resurrected (and improved) tooltip for cycle event tool

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/file-explorer/file-explorer.component.html
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/file-explorer/file-explorer.component.test.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/file-explorer/file-explorer.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/cycle-events/cycle-events.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/event-data-explorer/event-data-explorer-dialog/event-data-explorer-dialog.component.test.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/event-data-explorer/event-data-explorer-dialog/event-data-explorer-dialog.component.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/services/file-loader.service.ts

This is actually useful in case of automatic file reload when cycling on live events. Without it, new events are not loaded as the cache enters the game.
This included extending the file-loader API to allow any options to be passed when loading a file.
It allows the following syntax in json files uses by the loader component : 
```json
[
{"name":"Live events.json",  "url":"https:\/\/.../liveEvents.json.zip", "nocache":"true"},
{"name":"2023/FirstCollisions2023.json",  "url":"\/assets\/files\/lhcb\/FirstCollisions2023.json.zip"},
...
]
```

Allowed to specify "no-cache" for file loading

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/view-options/cartesian-grid-config/cartesian-grid-config.component.html

Disabled the grid translation, while the translation using mouse click is active.

Fix: restrict simultaneous grid translation, both by pointer and by values

---

README.md

As you know, thanks to the `Belle II Event Display with Phoenix` project during the Google Summer of Code 2023, in Belle II we now have a shiny new event display based on Phoenix: https://display.belle2.org/
If you don't mind, I would like to mention it in the README file of this project.
(In case you are curious, the code is publicly available on GitHub: https://github.com/belle2/display)

Add a reference to the Belle II event display in the README file

---

package.json
packages/phoenix-event-display/src/managers/ui-manager/color-options.ts
packages/phoenix-event-display/src/managers/ui-manager/index.ts
yarn.lock

Attempt to fix issues making a new release:
https://github.com/HSF/phoenix/actions/runs/8338400002
Specifically:
```
Successfully replaced in file /home/runner/work/phoenix/phoenix/docs/api-docs/index.html
file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:16599
throw new UndefinedParserError(
^
UndefinedParserError: No parser could be inferred for file "/home/runner/work/phoenix/phoenix/yarn.lock".
at normalizeFormatOptions (file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:16599:15)
at formatWithCursor (file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:18220:52)
at file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:21420:12
at async Module.format2 …
```

Update prettier and fix linting

---

packages/phoenix-event-display/package.json
packages/phoenix-ng/package.json
packages/phoenix-ng/projects/phoenix-ui-components/package.json
yarn.lock

This confirms that #658 is fixed (see the ticket for the discussion)
See https://github.com/mrdoob/three.js/releases/tag/r165 for details of what has changed compared to 0.162

Update to three 0.165

---

guides/developers/set-up-phoenix.md

- Works for updated angular
- Uses the standalone controls recommended since Angular 17+

Update of set-up-phoenix instructions for Angular 17+

---

packages/phoenix-event-display/src/helpers/file.ts
packages/phoenix-ng/projects/phoenix-app/src/app/home/home.component.ts

Whilst investigating the various reports of issues with loading configs, I saw that we have an error reporting in `file.ts` "TypeScript: Illegal constructor"
As explained in https://stackoverflow.com/a/26221525, we cannot use constructors for DOM elements

Fix for "TypeScript: Illegal constructor"

---

packages/phoenix-event-display/src/helpers/file.ts
packages/phoenix-event-display/src/loaders/phoenix-loader.ts
packages/phoenix-event-display/src/managers/ui-manager/index.ts
packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-node.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts

This has some fixes for #685 - now the label text should be updated.
Also for #633 - as long as you load the label file first, then load the configuration, the labels should get the correct colour (for a reason I've not yet worked out, the GUI colour is changed, but incorrectly!)
Next: make it so that the label text is saved with configuration (will get around the ordering issue)

Improve labels

---

packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-node.ts

I noticed that the Label collections colour was loaded when loading a configuration file, but not the colours of individual labels. This fixes this. 
Related to #685 and #633

Colour sub-labels too

---

.github/workflows/main.yml
.husky/pre-commit
packages/phoenix-event-display/src/lib/models/cut.model.ts
packages/phoenix-event-display/src/loaders/phoenix-loader.ts
packages/phoenix-event-display/src/managers/state-manager.ts
packages/phoenix-event-display/src/managers/ui-manager/color-options.ts
packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-node.ts
packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-ui.ts
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/phoenix-menu/phoenix-menu-item/phoenix-menu-item.component.html

https://github.com/HSF/phoenix/issues/689

[#689] Reset cut is not updating view

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.scss

Fixed collection info table for smaller screens like Ipads
Before:
After:

Fixed collection-info table-Issue#206

---

packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts

The edm4hep.json files report this error otherwise:
```
Error: Invalid file format!
```

Fixing loading of EDM4hep event data files

---

packages/phoenix-event-display/src/loaders/phoenix-loader.ts
packages/phoenix-event-display/src/managers/three-manager/color-manager.ts
packages/phoenix-event-display/src/managers/ui-manager/color-options.ts
packages/phoenix-event-display/src/managers/ui-manager/index.ts

Fixes issue, where hit color is not reflected in the phoenix menu.
From:
To:
Fixes also the random button.

Show hit color back in the Phoenix menu

---

packages/phoenix-event-display/src/loaders/edm4hep-json-loader.ts

The associations or links in EDM4hep have now `from` and `to` instead of `sim` and `rec`. This PR allows both of the link types.

EDM4hep loader: Allowing new style of links (to, from)

---

packages/phoenix-event-display/src/event-display.ts

Seems this was broken by mistake in #675

Fixed hierarchy support in the phoenix menu when loading from GLTF
