- js/jsdisplay.js
- phoenix_TrackML.html
Addresses: #7 
Hi,
I have tried adding icon support to preset views. The icons appear at the middle top.
I am not sure if fontawesome icons are doing a good enough job. Should we use custom made images instead?
However, what do you think of it so far?
> Preset Views

- css/style.css
- index.html
- phoenix_ATLAS.html
- phoenix_TrackML.html
- phoenix_geom.html
Hi,
This improves the formatting and separates styles. There is nothing added or deleted.
> Formatting markup and separating styles

- src/app/services/three.service.ts
- src/app/services/ui.service.ts
For enhancement purposes I have added the ability to switch between orthographic and perspective view. I have also included some new controls in the GUI. The controls include a toggle to switch camera view mode and additional alignment options.
> Added the ability to switch between orthographic and perspective view.

- src/app/home/home.component.html
Hi,
Some of the classes being used for the homepage pricing-header can be removed without affecting its responsive behavior.
> Use minimal classes for homepage header

- src/app/components/home/home.component.ts
- src/app/services/three.service.ts
Hi,
There seem to have been issues switching themes.
For starters, the home page did not recognize which theme was being used and defaulted to white theme while the experiments used dark theme since they were checking which theme to use through`UIService::showUI()`.
Also the loading functions were arbitrarily setting the eventDisplay background to dark. Since UI service chooses that now, there is no need of it anymore.
> Fix theme switching issues

- src/app/components/ui-menu/object-selection/object-selection.component.ts
- src/app/services/eventdisplay.service.ts
- src/app/services/loaders/jivexml-loader.ts
- src/app/services/three.service.ts
- src/app/services/ui.service.ts
This is a bit of a WIP, so I'm making it a PR.
The idea is you can mouseover to highlight objects, and then click once you get the right one. This doesn't work for non-dark mode (at least, not well - I'm really not sure why ... perhaps it needs to know the background colour?) nor for tracks (which probably we need to handle specially)
Anyway, have a look! 
Also tagging @9inpachi
> Master add object highlighting

- src/app/services/ui.service.ts
Closes #62 
Hi, a "Show" checkbox has been added to the"Geometry" folder that controls the visibility of all geometries added through the `addGeometry()` method.
> Global checkbox for showing/hiding geometries

- src/app/services/three.service.ts
Hi,
For object highlighting, instead of going through all the intersects, I think it's fine if we select the first element. The selections at this point are not small enough to have more intersects. Removing the for loop increases the FPS by 10, so I think it's worth it.
Besides that, using a cursor when the selection mode is on makes it easier for the user to know that an object is being hovered on.
> Improving object highlighting code

- src/app/services/eventdisplay.service.ts
Closes #42
Hi,
Added a function to enable using event display service methods in console.
I added the ones I think would be useful. If more are to be added, let me know, I will push to this PR.
Thanks. :)
> Call event display service functions via console

- src/app/services/loaders/phoenix-loader.ts
Hi,
I have added a function `getCuts(): Cut[]` which checks if cuts are available in the collection data and returns cuts available if they exist.
Please let me know if there are any problems.
> Check if cuts available in data

- src/app/services/three/renderer-manager.ts
Should make output look better.
Before:
After:
> Set the pixelRatio to be that of the device. 

- src/app/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
- src/app/components/ui-menu/event-selector/event-selector.component.scss
- src/app/components/ui-menu/info-panel/info-panel-overlay/info-panel-overlay.component.html
- src/app/components/ui-menu/info-panel/info-panel-overlay/info-panel-overlay.component.scss
- src/app/components/ui-menu/object-selection/object-selection-overlay/object-selection-overlay.component.html
- src/app/components/ui-menu/overlay-view/overlay-view-window/overlay-view-window.component.html
- src/app/components/ui-menu/overlay/overlay.component.html
- src/app/components/ui-menu/overlay/overlay.component.scss
- src/app/components/ui-menu/overlay/overlay.component.ts
- src/app/services/infologger.service.ts
- src/app/services/three/selection-manager.ts
- src/styles.scss
I pulled in a fix from @9inpachi 's RK branch (06e8993043e3976f18be32e7285c3654d4fb1db5) and also made some layout tweaks (smaller fonts, so we can see more, and don't limit the width of overlays, for the same reason)
> Layout improvements and misc fixes

- src/app/services/three/controls-manager.ts
Hi,
Generalized the `ControlsManager.lookAtObject(uuid)` function so it works with any new physics object added.
(Was not working for MuonChambers in CMS)
> Generalize 'lookAtObject'

- src/app/components/phoenix-menu/pheonix-menu-item/phoenix-menu-item.component.scss
- src/app/components/phoenix-menu/phoenix-menu.component.scss
- src/app/components/ui-menu/experiment-info/experiment-info.component.html
- src/app/components/ui-menu/experiment-info/experiment-info.component.scss
- src/app/components/ui-menu/menu-toggle/menu-toggle.component.html
- src/app/components/ui-menu/ui-menu.component.scss
- src/app/components/ui-menu/zoom-controls/zoom-controls.component.html
- src/app/services/three/selection-manager.ts
**Note:** To be merged after PR 119 
Hi,
This fixes major bugs and limitations of using Phoenix on mobile devices. Even some common functions like the UI menu were not working on mobile devices. Now Phoenix is complete usable on mobile devices.
* Made phoenix menu completely responsive and functional on mobile devices including advanced options
* Moved experiment info to top left
* Fixed responsive behavior of experiment info and made only the experiment logo visible on small screens
* Fixed UI menu not horizontally scrolling on mobile devices (because of material tooltips)
* Made possible to hold zoom in and zoom out on mobile devices
* Improved overall object selection by optimizing code and making selection/highlighting more accurate
* Made object selection work on mobile devices …
> Major fixes for mobile devices

- packages/phoenix-event-display/src/loaders/jivexml-loader.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/three/selection-manager.ts
Added "pretty print" functionality, which let's developers chose which information to show on object selection:
Read some more variables from JiveXML and add protections against duplicate and problematic collections.
Fixed issue with MeV vs GeV for pT.
> Jive xml improvements

- packages/phoenix-app/src/app/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts
- packages/phoenix-event-display/src/loaders/objects/cms-objects.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/three/selection-manager.ts
Hi,
This extends and generalizes the pretty printing if object parameters in selection and also adds it to parameters in collections info panel.
* Function to get pretty printed parameters based on defined symbols
* Pretty printed parameters in selection panel
* Pretty printed parameters in collections info panel
* Using the default parameter value if no pretty symbol defined for the parameter
**Before**
**After**
> Pretty printed object parameters

- package.json
- packages/phoenix-app/package.json
- packages/phoenix-event-display/src/three/index.ts
- packages/phoenix-event-display/src/three/renderer-manager.ts
- packages/phoenix-event-display/src/three/vr-manager.ts
Closes #151
This fixes the bugs with geometries in VR mode and does not use `EffectManager` when rendering the scene in VR mode.
> Fix bugged scene in VR mode

- packages/phoenix-app/src/app/sections/atlas/atlas.component.ts
- packages/phoenix-event-display/src/extras/configuration.model.ts
- packages/phoenix-event-display/src/three/controls-manager.ts
- packages/phoenix-event-display/src/three/index.ts
This adds a defaultView to the configuration, and moves the ATLAS defaultView to a position which is a bit more performant, and perhaps less confusing.
> Add default view

- packages/phoenix-app/src/app/sections/atlas/atlas.component.ts
ONLY FOR ATLAS
This adds the ability to load an event by specifying a file through the URL.
**Cases:**
1. If both `file` AND `type` parameters are not defined, the default event (JiveXML) will be loaded
1. If both `file` AND `type` parameters are defined, the event path in the URL will be used
1. Both `file` AND `type` are required for loading an event through the URL. If neither  defined, the default event will be used
**Example URLs:**
* http://localhost:4200/atlas?file=assets/files/FJiveXML/JiveXML_359310_3066561649.xml&type=jivexml
* http://localhost:4200/atlas?file=assets/files/event_data/atlaseventdump2.json&type=json
* http://localhost:4200/atlas (default event)
> feat(app): load event from URL query params in ATLAS

- CONTRIBUTING.md
- README.md
- guides/developers.md
Fixes some link typos 
Add commit message guidelines (fixing #147)
> Documentation improvements

- packages/phoenix-app/README.md
- packages/phoenix-app/package.json
- packages/phoenix-app/src/app/app.module.ts
This is to enable us to deploy to a server at CERN and have URL file and config work.
> feat(app): Add a deploy:atlas script. Use hashed routes.

- packages/phoenix-event-display/package.json
- packages/phoenix-ng/package.json
- packages/phoenix-ng/projects/phoenix-ui-components/package.json
> build(event-display): update to threejs 0.122

- packages/phoenix-ng/package-lock.json
- packages/phoenix-ng/package.json
- packages/phoenix-ng/projects/phoenix-ui-components/ng-package.json
- packages/phoenix-ng/projects/phoenix-ui-components/package.json
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/phoenix-menu/pheonix-menu-item/phoenix-menu-item.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/phoenix-menu/pheonix-menu-item/phoenix-menu-item.component.scss
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/phoenix-ui.module.ts
Closes #192 
This updates the ngx-slider to the latest version.
> Upgrade to ngx-slider

- .tugboat/config.yml
To be merged if #190 is resolved with tugboat as the preference.
Needs HSF org admins to create an account on tugboat.qa and add this repository and enable previews on pull requests.
> Tugboat for PR staging

- packages/phoenix-event-display/src/three/import-manager.ts
> Assign the right name to geometries

- packages/phoenix-event-display/src/ui/phoenix-menu/phoenix-menu-node.ts
> Keep children toggle state in Phoenix menu

- .github/workflows/build-and-test.yml
- packages/phoenix-event-display/package.json
- packages/phoenix-event-display/src/loaders/objects/cms-objects.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
> Use per physics object color and not collection color

- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
> Add eta and phi cuts for Tracks

- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
- packages/phoenix-event-display/src/three/scene-manager.ts
- packages/phoenix-event-display/src/ui/index.ts
Closes #253 
Added scaling for CaloClusters and opacity and wireframing options for all collections.
> Options for CaloClusters

- packages/phoenix-event-display/src/event-display.ts
- packages/phoenix-event-display/src/helpers/active-variable.ts
- packages/phoenix-event-display/src/index.ts
- packages/phoenix-event-display/src/managers/state-manager.ts
- packages/phoenix-event-display/src/three/index.ts
- packages/phoenix-event-display/src/three/selection-manager.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.spec.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/object-clipping/object-clipping.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/object-clipping/object-clipping.component.spec.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/object-clipping/object-clipping.component.ts
> Fix UI binding for clipping

- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
- packages/phoenix-event-display/src/managers/state-manager.ts
> Use run and event number for save config name

- packages/phoenix-event-display/src/three/scene-manager.ts
feat(event-display) : add labels to axes
Fixes #265
Has parameters for controlling label and scale via UI one day.
> feat(event-display) : add labels to axes

- packages/phoenix-event-display/src/helpers/constants.ts
- packages/phoenix-event-display/src/helpers/coordinate-helper.ts
- packages/phoenix-event-display/src/loaders/jivexml-loader.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
- packages/phoenix-event-display/src/three/scene-manager.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts
Add missing energy, which is currently drawn as a dotted line.
> Draft: Add missing energy

- packages/phoenix-event-display/src/event-display.ts
- packages/phoenix-event-display/src/managers/state-manager.ts
- packages/phoenix-event-display/src/ui/index.ts
Closes #261
@EdwardMoyse let me know if this is fine.
> Keep state of event data folder on event switch

- packages/phoenix-event-display/src/loaders/jivexml-loader.ts
This works by removing closeby hits
It's definitely better now, but still not perfect.
There's not a lot more that can be done though - any smoothing risks moving the tracks unphysically
The real solution is to fix the input data.
Before:
After:
> fix(event-display): attempt to improve track extension

- packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.html
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/cms/cms.component.html
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.html
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/io-options/io-options.component.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ui-menu.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ui-menu.component.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/index.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/services/extras/event-data-import.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/services/index.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/types/index.ts
Closes #281 
This allows support for adding custom event data import options and adds option to import LHCb data.
> Option to allow custom event data import options

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
Didn't reserve space in Float32Array (oops).
> fix(event-display): fix drawing of hits

- packages/phoenix-event-display/src/helpers/rk-helper.ts
- packages/phoenix-event-display/src/loaders/jivexml-loader.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
Quite a few cleanups and fixes.
The most important fix is the one to cluster rendering, which closes #289 and another where the JiveXML tracks were sometimes drawn in the wrong place.
For the tracks, I'm still trying to debug an issue with JiveXML tracks apparently not always rendering correctly.
I've disabled using measurements to extend tracks until this is understood.
> Misc fixes

- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ss-mode/ss-mode.component.scss
> Show overlays in SS mode

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/managers/three-manager/color-manager.ts
- packages/phoenix-event-display/src/managers/ui-manager/color-options.ts
- packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/config-types.ts
- packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-node.ts
- packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-ui.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/phoenix-menu/pheonix-menu-item/phoenix-menu-item.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/ss-mode/ss-mode.component.spec.ts
Hi,
This adds color by vertex option and types for Phoenix menu. It also only shows configs for selected color by option.
* Add detailed types for Phoenix menu configurations
* Add option to color tracks by Vertex
* Add ability to filter and show only a selected group of configs
* Fix tests not working for fullscreen
> Color by Vertex option

- packages/phoenix-event-display/src/helpers/constants.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
Hello there, so, based on our discussion, i tried to add the new physics object, `PlanarCaloCell` and although it is somewhat successful there are some little problems that need to be fixed in order to be able for the merge to be done! 
1. As you can see on the screenshot below, the calorimeters show correctly the energy deposits but they are not placed correctly. What is needed to be done: Each time a new cell is being read from the file and added to the event-display it needs to transform itself automatically, from the original default position to each position given by the plane from the .json file. Even though I tried to do that, I was not able to make it work and I would kindly request for your help on that. 
2. And the second not so critical problem is that, I'm not quite sure how …
> Add new physics object

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
@andrewpap22 I finally got around to checkout your code. Here is a refactor of the code. I didn't have a good look at the event data earlier but now things were clear.
We had the actual collection array in `eventData.PlanarCaloCells[collection]['cells']` (notice the 'cells' object) that's why the function `addObjectType` wasn't picking it up. That function looks for an array of objects directly inside `eventData.PlanarCaloCells[collection]` but we had `cells` and `plane` inside instead of an array. ;)
Hope things are clear now. You did a great job and I am sure you were able to learn a lot. Feel free to ask anything that pops up. I finally have some time to spare for a couple of days. ^_^
> Improved handling of PlanarCaloCells

- packages/phoenix-event-display/src/helpers/coordinate-helper.ts
- packages/phoenix-event-display/src/loaders/jivexml-loader.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
added some new cut types (d0,z0)
more protections for JiveXML
add angleAreSane() check to CoordinateHelper
> Attempt to improve robustness of track import

- packages/phoenix-event-display/src/managers/three-manager/scene-manager.ts
> Persist cuts when collection is toggled

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
> Fix params of hits

- packages/phoenix-ng/angular.json
- packages/phoenix-ng/projects/phoenix-app/src/environments/environment.ts
- packages/phoenix-ng/projects/phoenix-app/src/polyfills.ts
- packages/phoenix-ng/projects/phoenix-app/src/test.ts
- packages/phoenix-ng/projects/phoenix-ui-components/_theming.scss
- packages/phoenix-ng/projects/phoenix-ui-components/src/test.ts
- packages/phoenix-ng/yarn.lock
Closes #315 
@EdwardMoyse I think everything works fine now. Could you also check so we can merge?
> Fix Angular bugs after update to v12

- packages/phoenix-event-display/src/helpers/rk-helper.ts
- packages/phoenix-event-display/src/loaders/jivexml-loader.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
Includes many fixes such as:
- no longer limit jet lengths since we can scale them bb41683 (which fixes #318 )
- better handling of JiveXML objects (pt and fix cuts to match, out-of-bounds angles etc)
- handle compound objects consistently (and added electron and photon which fixes #319 )
- refactored some elements of the runge kutta
> Misc atlas fixes

- packages/phoenix-event-display/src/managers/state-manager.ts
- packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-node.ts
Closes #334
This fixes error being thrown on loading state from the Phoenix menu.
* Fix load state throwing error
* Fix collection color not working with load state
> Fix load state option

- packages/phoenix-event-display/src/loaders/jivexml-loader.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
> Draw jets with correct width

- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
Should fix #336.
Better solution discussed in #339
> fix(event-display): increase max cut value for jets

- packages/phoenix-event-display/src/managers/three-manager/controls-manager.ts
> Fix labels not being added for electrons

- packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts
> Do not load local config if set in URL

- scripts/api-read-files/helpers.php
- scripts/api-read-files/read-files.php
With this, large files can be read by the app because the PHP script can't read and output large files because of limitations on the server side.
> Update read files script to return file URL

- packages/phoenix-event-display/src/managers/three-manager/scene-manager.ts
> Fix jets disappearing on scaling to 0

- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.scss
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts
With reference to issue #378, I added a checkbox to hide invisible objects in collections
> Added a checkbox to hide invisible objects in collections

- packages/phoenix-ng/angular.json
- packages/phoenix-ng/package.json
- packages/phoenix-ng/projects/phoenix-ui-components/_theming.scss
- packages/phoenix-ng/projects/phoenix-ui-components/package.json
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/phoenix-ui.module.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.scss
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/share-link/share-link-dialog/share-link-dialog.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/share-link/share-link-dialog/share-link-dialog.component.spec.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/share-link/share-link-dialog/share-link-dialog.component.ts
- packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/view-options/view-options.component.html
- yarn.lock
> Generate QR code in shareable link dialog

- .github/workflows/main.yml
- .github/workflows/release.yml
> Push to release with docker

- packages/phoenix-ng/package.json
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/phoenix-ui.module.ts
- packages/phoenix-ng/projects/phoenix-ui-components/package.json
- yarn.lock
> Use rp3e11's fork of ngx-slider

- guides/developers/event-display.md
- guides/developers/set-up-phoenix.md
Hello maintainers, I was going through the documentation and found some of the links which pointed to the wrong places. Hopefully, this PR fixes that. 
I have been following CERN for quite some time and kudos to all the superb work that has been done.
Looking forward to contributing more towards phoenix!
Thanks.
> Add correct links in developer guide

- packages/phoenix-event-display/src/event-display.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
- packages/phoenix-event-display/src/managers/ui-manager/dat-gui-ui.ts
- packages/phoenix-event-display/src/managers/ui-manager/index.ts
- packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-ui.ts
- packages/phoenix-event-display/src/managers/ui-manager/phoenix-ui.ts
- packages/phoenix-event-display/src/tests/managers/ui-manager/index.spec.ts
> Create and use a common interface for UI menus

- packages/phoenix-event-display/src/extras/configuration.ts
- packages/phoenix-event-display/src/managers/three-manager/index.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
> Add clipping planes to configuration

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
This allows to display hits as boxes. The syntax is identical to line, meaning 6 coordinates per hit. The first 3 coordinates define the center of the box, the 3 others are the sizes along the 3 main axis.
At this stage, the box cannot be oriented. Its edges are parallel to the main axis
> Introduced new type of Hits rendering, namely Box

- guides/developers/event-display.md
Fixes: https://github.com/HSF/phoenix/issues/432  
Please let me know if something else needs to change as well.
> Update documentation for managers

- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
Including more types of hits (FT, Muon in particular) and vertices. Tracks are also colored according to their particle type
> new event data for LHCb

- packages/phoenix-event-display/src/extras/preset-view.model.ts
- packages/phoenix-event-display/src/managers/three-manager/controls-manager.ts
- packages/phoenix-event-display/src/managers/three-manager/import-manager.ts
- packages/phoenix-event-display/src/managers/ui-manager/index.ts
- packages/phoenix-event-display/src/tests/managers/ui-manager/index.spec.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/cms/cms.component.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/playground/playground.component.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/trackml/trackml.component.ts
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/view-options/view-options.component.spec.ts
Target was always 0,0,0 up to now. this applies to default view and all predefined views.
On the way, predefined views for LHCb have been improved
This should only be merged after #443 #442 #444
> Allow to define a target point in views

- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
previous code was creating errors when reloading the same event again
closes #452
> Fixed loading of PlanarCaloCells

- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.html
Not to be merged for now, as the gui is not optimal (cycle through events button not in the right place)
> Changes in LHCb data and gui

- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/ss-mode/ss-mode.component.scss
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/ui-menu-wrapper/ui-menu-wrapper.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/ui-menu-wrapper/ui-menu-wrapper.component.scss
> Fix toolbar not showing in SS mode on LHCb

- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
Including an example of setting default clipping in a preset view
> New geometry and preset views for LHCb

- packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.html
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/cms/cms.component.html
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/README.md
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/experiment-info/experiment-info.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/experiment-info/experiment-info.component.ts
> Allow customization of options in experiment info component

- packages/phoenix-event-display/src/event-display.ts
- packages/phoenix-event-display/src/managers/three-manager/import-manager.ts
- packages/phoenix-event-display/src/managers/three-manager/index.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
> Drop unused transparency argument in loadGLTFGeometry

- packages/phoenix-event-display/src/event-display.ts
- packages/phoenix-event-display/src/managers/three-manager/import-manager.ts
- packages/phoenix-event-display/src/managers/three-manager/index.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts
- packages/phoenix-ng/projects/phoenix-app/src/app/sections/lhcb/lhcb.component.ts
Although we did not yet fix #39, this makes things a bit more usable, at least there are no "holes"
Depends on and includes #488
> When loading gltf, make faces double sided

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/loaders/objects/tracks.ts
- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
- packages/phoenix-event-display/src/managers/three-manager/animations-manager.ts
- packages/phoenix-event-display/src/managers/three-manager/import-manager.ts
- packages/phoenix-event-display/src/managers/three-manager/index.ts
- packages/phoenix-ng/projects/phoenix-app/src/zone-flags.ts
* Merge meshes of the detector that share the same materials
* Merge Calo Cells
* Implement a tracks mesh that contains multiple instance of tracks (to reduce the number of draw calls) and implement features from https://github.com/spite/THREE.MeshLine
On the LHCb event viewer the framerate goes from 7fps to above 40fps.
> Merge meshes to improve performances

- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts
This adds support for zipped JiveXML files with the format JiveXML_XXX_YYY.zip
Currently this is pretty ugly, so it's a draft right now. 
Related to #498
> Support reading JiveXML.zip

- yarn.lock
> Simpler fix for phoenix-ui-components compilation after Angular 14 update

- packages/phoenix-event-display/src/helpers/zip.ts
- packages/phoenix-event-display/src/index.ts
- packages/phoenix-event-display/src/loaders/jivexml-loader.ts
- packages/phoenix-event-display/src/managers/url-options-manager.ts
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts
- yarn.lock
Failed attempt to fix #505
@9inpachi - I probably need your help here. I think I've made a complete mess of the promises. :-(
Hopefully you can see what I was trying to do?
It fails with:
```
Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'firstEvent.getAttribute') getEventData@http://localhost:4200/main.js:7384:30 
```
I'll attach a zipped JiveXML file.
> Unzip-jivexml-from-url

- guides/developers/test-setup.md
As agreed upon, here it is. If anything is more or less, please let me know. 
@9inpachi @EdwardMoyse 
Thanks a lot for your time!
> Add documentation for new testing setup in Phoenix

- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
Adds scaling already defined scaling for the calo cells.
> Add scaling for calo cells

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/managers/url-options-manager.ts
When using Phoenix loader, the position of the vertex was not properly loaded.
> Fixing loading of the vertex position

- packages/phoenix-event-display/src/managers/url-options-manager.ts
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.html
Improving visual appearance of the modal
> Tidy up import/export modal

- packages/phoenix-event-display/src/browser.ts
- packages/phoenix-event-display/src/index.ts
- packages/phoenix-event-display/src/loaders/edm4hep-json-loader.ts
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts
- packages/phoenix-ng/projects/phoenix-ui-components/lib/services/extras/event-data-import.ts
Adds possibility to load event data in edm4hep dumped into json file.
> feat(event-display): edm4hep JSON loader

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
Adds side and length for the calo cells/clusters
> feat(event-display): adds side and length for the calo cells

- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/event-data-explorer/event-data-explorer-dialog/event-data-explorer-dialog.component.ts
It now supports extensions .json.zip and .xml.zip
> Added zip file support in data-explorer-dialog component

- packages/phoenix-event-display/src/loaders/edm4hep-json-loader.ts
- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
- packages/phoenix-event-display/src/tests/loaders/objects/phoenix-objects.test.ts
Introduce several additional members to the phoenix event objects. Most importantly radius at which calorimeter cell/cluster is drawn.
> feat(event-display): cell radius

- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/embed-menu/experiment-link/experiment-link.component.ts
The idea then is we open the event with full controls in full phoenix.
Thanks to @9inpachi  for the code!
Fixes #527
> Just strip embed in experiment-link

- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/embed-menu/experiment-link/experiment-link.component.ts
I messed up with  #562 by accidentally merging - then somehow a next commit when directly to main. Anyway this should fix it.
> Fix compilation issue caused by accidental commit to main

- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/experiment-info/experiment-info.component.scss
Another request from ATLAS, to make the experiment info font monospaced
> Request to change experiment info font to monospace

- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/view-options/cartesian-grid-config/cartesian-grid-config.component.html
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/view-options/cartesian-grid-config/cartesian-grid-config.component.spec.ts
- packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/view-options/view-options.component.html
Fix a linting issue caused by [#587](https://github.com/HSF/phoenix/pull/587).
> Fix linting error

- packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts
Closes #591
Make sure that we pass colo(u)r as a hex number rather than a string
> fix #591 - color should be int not string

- packages/phoenix-event-display/src/helpers/file.ts
This is NOT a clean solution but I do not know what else to try
> Attempt to workaround Issuing loading configuration on Safari #582

- packages/phoenix-event-display/package.json
- packages/phoenix-event-display/src/tests/helpers/coordinate-helper.test.ts
- packages/phoenix-ng/package.json
- packages/phoenix-ng/projects/phoenix-ui-components/package.json
- yarn.lock
As per the title, just a threejs update.
Tested locally, no problems spotted.
> Update Phoenix to three 0.160.0

- packages/phoenix-event-display/src/loaders/phoenix-loader.ts
* improved object naming
* do not try to extrapolate / clusterify objects that do not support that
* better protection for missing data
Below is an image showing:
* Muons (in green), drawn using the ID tracks they are linked to;
* Photons, drawn using their kinematic quantities to draw a representative cluster
* ID Tracks (in red)
> Add better supprt for Compound objects

- packages/phoenix-ng/angular.json
- packages/phoenix-ng/package.json
- yarn.lock
"This package has been deprecated. Please use the ng-packagr builder from @angular-devkit/build-angular instead."
> build-ng-packagr deprecated

- packages/phoenix-event-display/src/managers/three-manager/import-manager.ts
- packages/phoenix-event-display/src/managers/three-manager/index.ts
Similarly, try to output error to log
cc @sponce
> Revert error introduced in #656. 

- README.md
With `corepack`, Yarn version is specified in the `package.json`
> Update Yarn installation instructions
